apiVersion: v1
kind: Secret
metadata:
  name: git-01
  namespace: operator-data-replace-inline

  labels:
    #app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: operator-data-replace-inline

  annotations:
    datareplaceinline/config-type: git

stringData:
  #revision: "master"
  branch: "master"
  url: "https://github.com/jaberchez/kustomize-plugins"
  pathConfigFile: "config/config.yaml"

  # Format supported yaml, ini
  typeFile: "yaml"
  usingCredentials: "false"

  # If usingCredentials == "true"
  # 
  # Credentials type: userPassword, token, ssh
  credentials.type: ""

  # If credentials.type == "userpassword"
  # credentials.user
  # credentials.password

  # If credentials.type == "token"
  # credentials.token

  # If credentials.type == ssh
  # credentials.ssh.password
  # credentials.ssh.pem