apiVersion: v1
kind: Secret
metadata:
  name: vault-01
  namespace: operator-data-replace-inline

  labels:
    #app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: operator-data-replace-inline

  annotations:
    datareplaceinline/config-type: vault

stringData:
  server: "http://vault.vault.svc:8200"
  #usingCredentials: "true"
  credentials.type: "token"
  credentials.token: "R74FHU"
  